import path from "path";
import fs from "fs";
import { repoRoot } from "./env.js";

const ROOT = repoRoot();

/** Official install docs for flyctl (all platforms). */
export const FLY_CLI_INSTALL_DOCS_URL = "https://fly.io/docs/flyctl/install/";

export interface FlyTomlOptions {
  app: string;
  region: string;
  serverName: string;
  /** e.g. "8gb", "4gb" — passed to Fly [[vm]] memory */
  vmMemory: string;
}

/** Machine-writable fly.toml (setup overwrites this). astroneer-server-kit repo. */
export function renderFlyToml(o: FlyTomlOptions): string {
  const name = o.serverName.replace(/"/g, '\\"');
  return `# astroneer-server-kit — generated by make setup; edit app/region/vm then fly deploy
app = "${o.app}"
primary_region = "${o.region}"

[build]

[[restart]]
  policy = "on-failure"
  retries = 3
  processes = ["app"]

[env]
  DATA_DIR = "/data"
  ASTRONEER_SERVER_NAME = "${name}"
  ASTRONEER_GAME_PORT = "8777"
  ASTRONEER_CONSOLE_PORT = "8779"
  ASTRONEER_SERVER_ARGS = "-FullStdOutLogOutput"

[[mounts]]
  source = "astroneer_server_kit_data"
  destination = "/data"

[[vm]]
  memory = "${o.vmMemory}"
  cpu_kind = "shared"
  cpus = 4

[[services]]
  protocol = "tcp"
  internal_port = 8777
  processes = ["app"]

  [[services.ports]]
    port = 8777

[[services]]
  protocol = "udp"
  internal_port = 8777
  processes = ["app"]

  [[services.ports]]
    port = 8777

# Remote console (TCP) — not the game port; see ASTRONEER_CONSOLE_PORT / AstroServerSettings.ini ConsolePort
[[services]]
  protocol = "tcp"
  internal_port = 8779
  processes = ["app"]

  [[services.ports]]
    port = 8779
`;
}

export function writeFlyToml(opts: FlyTomlOptions): void {
  fs.writeFileSync(path.join(ROOT, "fly.toml"), renderFlyToml(opts), "utf8");
}

export function flyCmdSync(
  args: string[],
  env: Record<string, string | undefined>,
): { ok: boolean; code: number; stdout: string; stderr: string } {
  const r = Bun.spawnSync(["fly", ...args], {
    cwd: ROOT,
    env: { ...process.env, ...env, TERM: "dumb" },
    stdout: "pipe",
    stderr: "pipe",
  });
  return {
    ok: r.exitCode === 0,
    code: r.exitCode ?? 1,
    stdout: r.stdout.toString(),
    stderr: r.stderr.toString(),
  };
}

/**
 * Parse `fly ips list --json` stdout. Fly's API uses `Address` / `Type` (see fly-go IPAddress), not `addr` / `version`.
 * Skips egress rows; prefers dedicated ingress, then any ingress, then first public IPv4.
 */
export function parseFlyIpListJson(stdout: string): string | null {
  let data: unknown;
  try {
    data = JSON.parse(stdout.trim());
  } catch {
    return null;
  }
  if (!Array.isArray(data)) return null;

  const isDottedV4 = (s: string): boolean => /^(?:\d{1,3}\.){3}\d{1,3}$/.test(s.trim());

  const addrOf = (o: Record<string, unknown>): string | undefined => {
    const v = o.addr ?? o.address ?? o.Address ?? o.ip ?? o.IP;
    return typeof v === "string" && v.length > 0 ? v : undefined;
  };

  const typeOf = (o: Record<string, unknown>): string => String(o.type ?? o.Type ?? "");

  const verOf = (o: Record<string, unknown>): string | number | undefined => {
    const v = o.version ?? o.Version;
    if (typeof v === "string" || typeof v === "number") return v;
    return undefined;
  };

  const dedicated: string[] = [];
  const ingress: string[] = [];
  const anyV4: string[] = [];

  for (const row of data) {
    if (!row || typeof row !== "object") continue;
    const o = row as Record<string, unknown>;
    const t = typeOf(o);
    if (t.startsWith("egress")) continue;
    const a = addrOf(o);
    if (!a || !isDottedV4(a)) continue;
    const ver = verOf(o);
    if (ver === "v6" || ver === 6) continue;

    const trimmed = a.trim();
    if (t.includes("ingress") && t.includes("dedicated")) dedicated.push(trimmed);
    else if (t.includes("ingress")) ingress.push(trimmed);
    else anyV4.push(trimmed);
  }

  return dedicated[0] ?? ingress[0] ?? anyV4[0] ?? null;
}

/** First public (non-egress) IPv4 for the app from `fly ips list --json`. */
export async function flyListDedicatedIPv4(
  app: string,
  env: Record<string, string | undefined>,
): Promise<string | null> {
  const r = await flyCmdAsync(["ips", "list", "-a", app, "--json"], env);
  if (!r.ok) return null;
  return parseFlyIpListJson(r.stdout);
}

/**
 * Ensure the app has a dedicated IPv4 (Fly anycast); allocates one if missing.
 * Returns the address for setting ASTRONEER_PUBLIC_IP (matches inbound join IP, not egress).
 */
export async function ensureFlyDedicatedIPv4(
  app: string,
  env: Record<string, string | undefined>,
): Promise<{ ok: boolean; ipv4?: string; stderr?: string }> {
  let ip = await flyListDedicatedIPv4(app, env);
  if (ip) return { ok: true, ipv4: ip };
  const alloc = await flyCmdAsync(["ips", "allocate-v4", "-a", app, "-y"], env, { inheritIo: true });
  if (!alloc.ok) {
    return {
      ok: false,
      stderr: alloc.stderr.trim() || alloc.stdout.trim() || `fly ips allocate-v4 exited ${alloc.code}`,
    };
  }
  for (let i = 0; i < 8; i++) {
    if (i > 0) await new Promise(r => setTimeout(r, 400));
    ip = await flyListDedicatedIPv4(app, env);
    if (ip) return { ok: true, ipv4: ip };
  }
  return { ok: false, stderr: "IPv4 allocated but not listed — try: fly ips list -a " + app };
}

export async function flyCmdAsync(
  args: string[],
  env: Record<string, string | undefined>,
  opts?: { inheritIo?: boolean },
): Promise<{ ok: boolean; code: number; stdout: string; stderr: string }> {
  const proc = Bun.spawn(["fly", ...args], {
    cwd: ROOT,
    env: { ...process.env, ...env, TERM: "dumb" },
    stdout: opts?.inheritIo ? "inherit" : "pipe",
    stderr: opts?.inheritIo ? "inherit" : "pipe",
  });
  const code = await proc.exited;
  return {
    ok: code === 0,
    code,
    stdout: opts?.inheritIo ? "" : await new Response(proc.stdout).text(),
    stderr: opts?.inheritIo ? "" : await new Response(proc.stderr).text(),
  };
}

export function flyInstalled(): boolean {
  return Bun.spawnSync(["fly", "version"], { stdout: "ignore", stderr: "ignore" }).exitCode === 0;
}

/** True if `fly auth whoami` succeeds (user has run `fly auth login`). */
export function flyAuthLoggedIn(): boolean {
  if (!flyInstalled()) return false;
  const r = flyCmdSync(["auth", "whoami"], {});
  return r.ok;
}

/**
 * Run interactive `fly auth login` (browser / prompts) with stdio inherited.
 * Call while your TUI has released raw mode on stdin (e.g. Ink `useInput` inactive).
 */
export async function flyAuthLoginInteractiveAsync(): Promise<{ ok: boolean; code: number }> {
  const proc = Bun.spawn(["fly", "auth", "login"], {
    cwd:   ROOT,
    env:   process.env,
    stdin:  "inherit",
    stdout: "inherit",
    stderr: "inherit",
  });
  const code = await proc.exited;
  return { ok: code === 0, code };
}

/** Resolve an org slug for non-interactive `fly` (e.g. `fly tokens create org -o …`). */
export async function flyPrimaryOrgSlugAsync(): Promise<{
  ok: boolean;
  slug?: string;
  stderr?: string;
}> {
  const r = await flyCmdAsync(["orgs", "list", "-j"], {});
  if (!r.ok) {
    return { ok: false, stderr: r.stderr.trim() || r.stdout.trim() || `exit ${r.code}` };
  }
  try {
    const parsed = JSON.parse(r.stdout.trim()) as unknown;
    if (Array.isArray(parsed)) {
      for (const row of parsed) {
        if (!row || typeof row !== "object") continue;
        const o = row as { slug?: string; Slug?: string };
        const slug = o.slug ?? o.Slug;
        if (typeof slug === "string" && slug.length > 0) return { ok: true, slug };
      }
    } else if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      // `fly orgs list -j` often returns { "personal": "Your Name", "other-org": "…" }
      const keys = Object.keys(parsed as Record<string, unknown>);
      const slug =
        keys.includes("personal") ? "personal" : keys.find(k => k.length > 0);
      if (slug) return { ok: true, slug };
    }
  } catch {
    /* fall through */
  }
  return {
    ok: false,
    stderr: "could not parse fly orgs list — run: fly orgs list",
  };
}

/**
 * Mint a long-lived **API token** (credential) scoped to your Fly **organization**.
 * This does **not** create a new organization — `fly tokens create org` is Fly’s name
 * for this token type. Non-interactive runs require `-o`; we use the first org from
 * `fly orgs list` (usually your personal org).
 * Prefer this over `fly auth token` for .env.
 */
export async function createFlyOrgDeployTokenAsync(
  name = "astroneer-server-kit",
): Promise<{ ok: boolean; token?: string; stderr?: string }> {
  const org = await flyPrimaryOrgSlugAsync();
  if (!org.ok || !org.slug) {
    return { ok: false, stderr: org.stderr ?? "no Fly org slug (fly orgs list)" };
  }
  const r = await flyCmdAsync(
    ["tokens", "create", "org", "-n", name, "-j", "-o", org.slug],
    {},
  );
  if (!r.ok) return { ok: false, stderr: r.stderr.trim() || r.stdout.trim() || `exit ${r.code}` };
  const raw = r.stdout.trim();
  try {
    const j = JSON.parse(raw) as { token?: string; Token?: string };
    const t = j.token ?? j.Token;
    if (typeof t === "string" && t.length > 0) return { ok: true, token: t };
  } catch {
    /* stdout may be raw token */
  }
  if (raw.length > 18 && !raw.startsWith("{")) return { ok: true, token: raw };
  return { ok: false, stderr: "unexpected token output from fly tokens create org" };
}

export function slugifyAppName(name: string): string {
  const s = name
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  return s.length >= 3 ? s : `astroneer-${s || "server"}`.slice(0, 40);
}
